### PR TITLE
Update Search using Typesense Docsearch

### PR DESCRIPTION
**Pull request by sontn1988**
### GOAL 
Apply typesense docsearch to replace current search

###  ISSUE
I wrote step by step how to apply typesense docsearch to replace current search in `README.md`
As follow step by step
- I could craw data from my Dev env to typesense

image

**I tried to update/add search bar to verify typesense docsearch:**
- I created file [searchbox.html](https://github.com/tradingstrategy-ai/docs/blob/dd096e289f25fb8821839b19ef9a05500c6f9487/source/_templates/searchbox.html) and save it to `source/_templates`
- I tried to rebuild  by command:
```
make clean-install-and-build-local-docs
```
- After re-build. I try to search in `searchbar` . But results are same 
image

### CODE REVIEW

**Comment by kenkunz** [comment]
@sontn1988, @miohtama:

The reason the JS wasn't loading properly was due to a conflict with `requirejs`. The only way I could get it working was to ensure the typesense JS is loaded _before_ `requirejs`. There are multiple versions of `requirejs` - one is defined in `conf.py`, the other one is coming from somewhere else that I couldn't find the source of (loading from cloudflare CDN). So I had to load the typescript JS is a hacky way (see commit / code comments for details).

In addition, I reconfigured the integration a bit to more closely follow the [Sphinx example](https://writeexperience.co/integrating-typesense-with-sphinx-readthedocs-template-a-step-by-step-guide/) referenced in the Typesense docs. See commit for details.

I also created search-scoped API key on the `jason.tradingstrategy.ai` instance and used this to configure `docsearch` in `search.html` template.

More work is needed to complete this:
- For prod, I think we'd want this running against the same cloud Typesense instance we use for `frontend` (until/unless we switch to self-hosted).
- Ideally we should figure out where the 2nd instance of `requirejs` is coming from load the typesense JS in a less hacky way.
- Look into and fix visual issues with the search field and modal
- Make sure the indexed entries point to the correct prod URLs
- Update docs to reflect the integration changes

**Comment by kenkunz** [comment]
FYI, I was able to get `typesense-docsearch` to load via `requirejs`, so removed the "hack workaround" that was forcing this to load first.

**Comment by sontn1988** [comment]
I updated:
- Update scraper config for production environment
- Craw data from production environment to typesense self host

**Comment by sontn1988** [comment]
Before merge PR:
We need add: `TYPESENSE_HOST`  and `TYPESENSE_API_KEY` in github secrect

**Review by kenkunz — APPROVED** [review]
lgtm!

**Pull request merged**
